### ISSUE TITLE
[Api]: 记账记录

### ISSUE THREAD

**Issue by hildxd** [colorful-dev/little-dear#20]
## Api
- [ ] crud
- [ ] 报销

## tips
得和账户还有类别，userId关联, 设计的时候还得价格type字段，用枚举值(支出/收入/转账)
**考虑到报销，还得多个已报销字段，报销不是把原记录delete了，而且新增了一条record并且修改了这个字段**

**Comment by hildxd** [comment]
![Image](https://github.com/colorful-dev/little-dear/assets/115518574/03b0d673-95bb-4e65-830b-404e655ba034)

**Comment by Nauxscript** [comment]
1

**Comment by Nauxscript** [comment]
![IMG_6778](https://github.com/colorful-dev/little-dear/assets/13010589/34726b73-5169-4a3a-bca8-5ac093a0510a)

还有退款功能；估计是和报销功能类似；

**Comment by Nauxscript** [comment]
账单记录基本字段

- id
- categoryId 记账类别 id
- categoryName 记账类别名称
- value 金额
- accountId 账户 id
- accountName 账户名称
- type 类别：收入 / 支出 / 转帐
- createTime 创建时间
- transactionTime 创建时间
- updateTime 更新时间
- createUserId 创建用户 id
- createUserName 创建用户 
- ledgerId 所属账本 id
- ledgerNmae 所属账本名称


接口定义：
- `bill`: 
    -  `get` 分页接口，默认获取最近 20 条记账记录
    - `post` 创建一条记账记录
- `bill/:id`: 
    - `get` 获取指定 id 的单条记账记录
    - `post` 删除
    - `put`  编辑

**Comment by Nauxscript** [comment]
分类表字段：

- id 
- name 分类名称
- createdAt 创建时间
- updateAt 更新时间
- icon 图标
